### ISSUE TITLE
Why not `pub struct RwLock<T: ?Sized>`?

### ISSUE THREAD

**Issue by sum-elier** [stjepang/async-rwlock#1]
As the title states, why not allow also unsized types as a bound? I downloaded the project, made it so the `struct` receives unsized types and all tests passed, so I suppose technically it works at least.

What are the differences in implementation between this crate and the implementation of `RwLock` found in `async_std`?

Thanks!

**Comment by yoshuawuyts** [comment]
I made a quick attempt to replace `async-std`'s internal impl with `async-rwlock` and ran into this restriction as well. Because it supports `?Sized` types we cannot switch over impls without it being a breaking change.

**Comment by sum-elier** [comment]
It's now solved with the latest release :)
