### ISSUE TITLE
Recursive reads cause deadlock

### ISSUE THREAD

**Issue by librelois** [stjepang/async-rwlock#2]
If a user does a recursive read while a writer has requested the lock, it causes a deadlock.

The documentation does not indicate that recursive reads are not supported. 
If this is intentional it should be pointed out in the documentation for the `RwLock` type and the `read()` method.

Here is the minimal test to reproduce the deadlock : 

```rust
    #[tokio::test]
    async fn recursive_read_lock() {
        let mutex = Arc::new(RwLock::new(0));
        let read1 = mutex.read().await;

        let mutex2 = mutex.clone();
        let task = tokio::spawn(async move {
            let mut write = mutex2.write().await;
            *write += 1;
        });

        tokio::time::delay_for(Duration::from_millis(200)).await;

        let read2 = mutex.read().await; // Await forever here

        drop(read1);
        drop(read2);
        task.await.expect("task panicked or cancelled");
        assert_eq!(1, *(mutex.read().await));
    }
```

**Comment by stjepang** [comment]
Hmm, `std::sync::RwLock` and `tokio::sync::RwLock` (at least on macos) behave exactly the same, so I don't expect this to be surprising.

Recursive reads are allowed and should work fine. The specific problem here is: a read lock cannot be acquired if somebody is attempting to acquire a write lock.

**Comment by librelois** [comment]
I'm trying to make my project async compatible and I use `parking_lot::RwLock`. So I wanted to use your crate to replace `parking_lot` in async mode. As the `parking_lot` documentation says: 

> Note that attempts to recursively acquire a read lock on a RwLock when the current thread already holds one may result in a deadlock.

I assumed that in the absence of precision, recursive reads were handled correctly. 

> Recursive reads are allowed and should work fine. 

No if recursive reads are allowed it should never cause a deadlock. parking_lot recognizes that they are not handled correctly with the `read' method and provides a `read_recursive' method for uses that need to allow recursive reads.

This is for example correctly handled by the `fast_async_mutex` crate the above test passes, even with their "write-preferring" variant.

> std::sync::RwLock

The std specifies that recursive lock reads can panic (this implies that it is not necessarily handled depending on the OS implementation).

So in any case it's not "obvious", it must be specified in the documentation :)

Indeed, tokio has the same problem, I I just opened a similar issue for them : https://github.com/tokio-rs/tokio/issues/2849

**Comment by stjepang** [comment]
Ah sorry, I think we're using same words to mean different things :) By "recursive reads should work" I meant if you do this:

```rust
let a = rwlock.read().await;
let b = rwlock.read().await;
```

That should work. The rule is just that writes take precedence over reads. I agree it would be good to document this!

**Comment by librelois** [comment]
>  I agree it would be good to document this!

Ok, I made a PR : https://github.com/stjepang/async-rwlock/pull/3 :)
